sudo: required
services:
  - docker

before_install:
  - docker build -t quanghuy9289/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true quanghuy9289/react-test npm run test -- --coverage

after_success:
  - docker build -t quanghuy9289/multi-client ./client
  - docker build -t quanghuy9289/multi-nginx ./nginx
  - docker build -t quanghuy9289/multi-server ./server
  - docker build -t quanghuy9289/multi-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push quanghuy9289/multi-client
  - docker push quanghuy9289/multi-nginx
  - docker push quanghuy9289/multi-server
  - docker push quanghuy9289/multi-worker
